server:
  port: 18080

spring:
  application:
    name: ruc-service-platform
  profiles:
    active: postgres
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.ruc.platform.**.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: postgresql

sa-token:
  token-name: Authorization
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false

wechat:
  miniapp:
    appid: wx9bb70b9dffc64858
    secret: c3e517aa09806f5546efface6d24af21

file:
  upload-path: ${user.home}/ruc-platform/uploads

logging:
  level:
    com.ruc.platform: debug
    com.ruc.platform.mapper: debug
    org.mybatis: debug
