spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:db-kingbase}:${DB_PORT:54321}/${DB_NAME:test}
    username: ${DB_USER:system}
    password: ${DB_PASSWORD:123456}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1200000
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: Initial baseline for Docker Kingbase
    clean-disabled: true
    validate-on-migrate: true

mybatis-plus:
  global-config:
    db-config:
      db-type: postgresql
